### PR TITLE
WIP: global: upgrade to app rdm v10

### PR DESCRIPTION
**Pull request by ppanero**
Things seem to work in v10.dev12. Just some minor css issues:

Screenshot 2022-10-03 at 21 25 39
Screenshot 2022-10-03 at 21 25 48

We might want to fine tune configuration.

### CODE REVIEW

**Review by slint — APPROVED** [review]
LGTM, thanks for dong the first pass :)

**Comment by slint** [comment]
Oh no, I missed the WIP :upside_down_face:

The Docker image build seems to be failing because of `@templates/custtom_fields` so maybe we're missing some upgrade steps.

**Comment by ppanero** [comment]
@slint I missed the `.gitkeep` on the folder 😮‍💨

**Comment by ppanero** [comment]
Made a new PR, merged, should have been correct now. No worries, I should have made it 'draft' pr.

**Pull request merged**
